"""script_py_template

Revision ID: 3f527904a79d
Revises: b3d4e5f6g7h8
Create Date: 2026-03-06 04:56:52.005933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f527904a79d'
down_revision = 'b3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('render_config', sa.JSON(), nullable=True),
    sa.Column('output_file_paths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_jobs')
    # ### end Alembic commands ###
