import React from "react";
import "./index.css";
import { Composition, staticFile } from "remotion";
import { MyComposition } from "./Composition";
import type { VideoCompositionProps } from "./types";

const FPS = 30;
const WIDTH = 1920;
const HEIGHT = 1080;

/** Auto-generated by test_pipeline_real.py */
const defaultProps: VideoCompositionProps = {
  videoSrc: staticFile("video test.mp4"),
  durationInSeconds: 546.55,
  fps: FPS,
  overlays: [
    {
      text: "The Marketing Revolution",
      start: 3.16,
      end: 8.16,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "Traditional Marketing",
      start: 11.16,
      end: 16.16,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "AI Versus Traditional",
      start: 27.0,
      end: 32.16,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    },
    {
      text: "Human Intuition",
      start: 166.4,
      end: 171.4,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "Late night brainstorming sessions",
      start: 174.4,
      end: 179.4,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/7668492/7668492-hd_1920_1080_25fps.mp4",
      search_query: "late night brainstorming session, creative team",
      highlight_word: "brainstorming"
    },
    {
      text: "Emotional Storytelling",
      start: 182.6,
      end: 187.4,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "AI: Data & Prediction",
      start: 190.47,
      end: 195.4,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "Creativity Meets Calculation",
      start: 238.77,
      end: 243.77,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "Coca Cola Case Study",
      start: 254.02,
      end: 259.02,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "OpenAI ChatGPT and Dall-E",
      start: 270.18,
      end: 275.18,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/30718280/13141866_540_360_30fps.mp4",
      search_query: "ChatGPT interface, Dall-E art generation, AI tools",
      highlight_word: "Dall-E"
    },
    {
      text: "120,000 Unique Artworks",
      start: 278.5,
      end: 283.02,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "Valuable user generated content",
      start: 293.6,
      end: 299.02,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/5081430/5081430-hd_1366_720_25fps.mp4",
      search_query: "diverse people creating digital content, user generated content",
      highlight_word: "content"
    },
    {
      text: "Traditional teams face planning challenges",
      start: 309.68,
      end: 315.02,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/7668496/7668496-hd_1920_1080_25fps.mp4",
      search_query: "creative team working late, traditional office, brainstorming",
      highlight_word: "challenges"
    },
    {
      text: "AI Turns Fans Into Creators",
      start: 318.08,
      end: 323.02,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    }
  ],
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="VideoWithOverlays"
        component={MyComposition}
        durationInFrames={Math.round(defaultProps.durationInSeconds * FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={defaultProps}
      />
    </>
  );
};
