import React from "react";
import "./index.css";
import { Composition, staticFile } from "remotion";
import { MyComposition } from "./Composition";
import type { VideoCompositionProps } from "./types";

const FPS = 30;
const WIDTH = 1920;
const HEIGHT = 1080;

/** Auto-generated by test_pipeline_real.py */
const defaultProps: VideoCompositionProps = {
  videoSrc: staticFile("video test.mp4"),
  durationInSeconds: 319.65,
  fps: FPS,
  overlays: [
    {
      text: "Marketing Revolution",
      start: 2.04,
      end: 6.04,
      mode: "CINEMATIC_CALLOUT",
      position: "left",
      highlight_word: "Revolution"
    },
    {
      text: "Traditional Marketing",
      start: 10.04,
      end: 14.04,
      mode: "SIDE_PANEL",
      position: "left",
      highlight_word: "Traditional"
    },
    {
      text: "AI Automation",
      start: 15.52,
      end: 20.52,
      mode: "B_ROLL_VIDEO",
      position: "left",
      url: "generated-broll/ai-automation-0e8bbab5c257.mp4",
      highlight_word: "Automation"
    },
    {
      text: "AI vs. Traditional",
      start: 27.3,
      end: 31.3,
      mode: "CINEMATIC_CALLOUT",
      position: "left",
      highlight_word: "Traditional"
    },
    {
      text: "Human Intuition",
      start: 41.62,
      end: 45.62,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Intuition"
    },
    {
      text: "Data & Personalization",
      start: 53.34,
      end: 57.34,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Personalization"
    },
    {
      text: "Creativity vs. Algorithm",
      start: 63.74,
      end: 67.74000000000001,
      mode: "CINEMATIC_CALLOUT",
      position: "left",
      highlight_word: "Creativity"
    },
    {
      text: "Coca-Cola: Create Real Magic",
      start: 106.13,
      end: 113.13,
      mode: "B_ROLL_VIDEO",
      position: "left",
      url: "generated-broll/coca-cola-create-real-ma-71b6cd288963.mp4",
      highlight_word: "Create"
    },
    {
      text: "Instant Creativity, Global Reach",
      start: 134.48,
      end: 138.72,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Creativity"
    },
    {
      text: "Heinz: AI Ketchup",
      start: 154.76,
      end: 160.76,
      mode: "B_ROLL_VIDEO",
      position: "left",
      url: "generated-broll/heinz-ai-ketchup-b54b04fbfb3a.mp4",
      highlight_word: "Ketchup"
    },
    {
      text: "Timeless Branding + AI",
      start: 191.84,
      end: 196.76,
      mode: "CINEMATIC_CALLOUT",
      position: "right",
      highlight_word: "Timeless"
    },
    {
      text: "Fast, Adaptive Creativity",
      start: 201.16,
      end: 207.72,
      mode: "SIDE_PANEL",
      position: "left",
      highlight_word: "Creativity"
    },
    {
      text: "Cost Savings & Efficiency",
      start: 211.08,
      end: 218.32,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Efficiency"
    },
    {
      text: "AI Replaces Non-Users",
      start: 231.92,
      end: 238.0,
      mode: "CINEMATIC_CALLOUT",
      position: "left",
      highlight_word: "Replaces"
    },
    {
      text: "The Hybrid Marketer",
      start: 246.86,
      end: 254.46,
      mode: "B_ROLL_VIDEO",
      position: "left",
      url: "generated-broll/the-hybrid-marketer-789fcda09677.mp4",
      highlight_word: "Marketer"
    },
    {
      text: "1. Human Storytelling",
      start: 258.62,
      end: 265.92,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Storytelling"
    },
    {
      text: "2. AI Insights & Delivery",
      start: 267.24,
      end: 273.16,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Insights"
    },
    {
      text: "3. Activate Automation",
      start: 274.52,
      end: 279.72,
      mode: "BOTTOM_TITLE",
      position: "bottom_center",
      highlight_word: "Automation"
    },
    {
      text: "AI With Human",
      start: 281.88,
      end: 285.88,
      mode: "CINEMATIC_CALLOUT",
      position: "left",
      highlight_word: "Human"
    },
    {
      text: "Human + AI = Scale",
      start: 291.44,
      end: 299.36,
      mode: "B_ROLL_VIDEO",
      position: "left",
      url: "generated-broll/human-ai-scale-01bc8a4da0a6.mp4",
      highlight_word: "Human"
    },
    {
      text: "Human & Machine",
      start: 304.72,
      end: 310.56,
      mode: "CINEMATIC_CALLOUT",
      position: "right",
      highlight_word: "Machine"
    }
  ],
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="VideoWithOverlays"
                component={MyComposition as unknown as React.ComponentType<Record<string, unknown>>}
        durationInFrames={Math.round(defaultProps.durationInSeconds * FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={defaultProps}
      />
    </>
  );
};
