import React from "react";
import "./index.css";
import { Composition, staticFile } from "remotion";
import { MyComposition } from "./Composition";
import type { VideoCompositionProps } from "./types";

const FPS = 30;
const WIDTH = 1920;
const HEIGHT = 1080;

/** Auto-generated by test_pipeline_real.py */
const defaultProps: VideoCompositionProps = {
  videoSrc: staticFile("video test.mp4"),
  durationInSeconds: 319.65,
  fps: FPS,
  overlays: [
    {
      text: "Marketing Revolution",
      start: 2.36,
      end: 7.36,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    },
    {
      text: "Traditional Marketing",
      start: 10.48,
      end: 15.36,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "AI Automation",
      start: 18.4,
      end: 23.36,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "AI vs. Traditional",
      start: 27.3,
      end: 32.3,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    },
    {
      text: "Human Intuition",
      start: 43.5,
      end: 48.3,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "Data & Prediction",
      start: 59.38,
      end: 64.3,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "Millions of Behaviors",
      start: 67.5,
      end: 72.5,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/36418628/15442044_640_360_25fps.mp4",
      search_query: "data analysis user behavior",
      highlight_word: "Millions"
    },
    {
      text: "Coca-Cola Case",
      start: 106.13,
      end: 111.13,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "ChatGPT & DALL-E",
      start: 114.33,
      end: 119.13,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "User Generated Content",
      start: 130.13,
      end: 135.13,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/7451171/7451171-hd_1920_1080_25fps.mp4",
      search_query: "user generated content social media",
      highlight_word: "Content"
    },
    {
      text: "Weeks of Planning",
      start: 146.04,
      end: 151.13,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "Fans into Creators",
      start: 154.16,
      end: 159.13,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    },
    {
      text: "DALL-E Draw Ketchup",
      start: 169.98,
      end: 175.13,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/8798087/8798087-hd_2048_1080_25fps.mp4",
      search_query: "AI drawing ketchup",
      highlight_word: "Ketchup"
    },
    {
      text: "Heinz Bottle",
      start: 178.26,
      end: 183.13,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "Timeless Branding",
      start: 186.52,
      end: 191.13,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    },
    {
      text: "Cost Savings",
      start: 213.04,
      end: 218.04,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "Hyper-Personalization",
      start: 222.0,
      end: 227.0,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "AI isn't replacing marketers",
      start: 231.92,
      end: 236.92,
      mode: "B_ROLL_VIDEO",
      position: "bottom_center",
      url: "https://videos.pexels.com/video-files/8480243/8480243-hd_1920_1080_25fps.mp4",
      search_query: "marketer using AI",
      highlight_word: "replacing"
    },
    {
      text: "Hybrid Marketers",
      start: 248.7,
      end: 253.7,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    },
    {
      text: "3 Hacks",
      start: 256.78,
      end: 261.7,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "AI Insights",
      start: 272.72,
      end: 277.7,
      mode: "SIDE_PANEL",
      position: "left"
    },
    {
      text: "AI with Human",
      start: 288.76,
      end: 293.7,
      mode: "CINEMATIC_CALLOUT",
      position: "right"
    },
    {
      text: "Partner with AI",
      start: 304.72,
      end: 309.7,
      mode: "CINEMATIC_CALLOUT",
      position: "left"
    },
    {
      text: "Human & Machine",
      start: 312.76,
      end: 317.7,
      mode: "BOTTOM_TITLE",
      position: "bottom_center"
    }
  ],
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="VideoWithOverlays"
        component={MyComposition}
        durationInFrames={Math.round(defaultProps.durationInSeconds * FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={defaultProps}
      />
    </>
  );
};
